### ISSUE TITLE
Add Generic instance

### ISSUE THREAD

**Issue by chexxor** [purescript-contrib/purescript-js-date#5]
The README and in-code docs say "...and has a `Generic` instance", but I don't see a Generic instance defined in this module. Am I missing something obvious?

I try to add `derive instance genericJsDate :: Generic JSDate` to this module below `foreign import data JSDate :: *`, but I get an error: "Cannot derive a type class instance, because the type declaration for JSDate could not be found." I found a note in the [0.9.1 PureScript release docs](https://github.com/purescript/purescript/releases/tag/v0.9.1) that implies this is a known issue, so maybe the docs here should be updated.

Thoughts?

My use-case: I'm trying to use the purescript-foreign-generic package to decode a JSON object I get from my API which has a date encoded as a ISO8601 string. Like this:

``` purescript
newtype ApiResponse = ApiResponse
{ name :: String
, createdDate :: JSDate
}

derive instance genericApiResponse :: Generic ApiResponse -- fails
-- because JSDate has no instance of Generic
```

**Comment by garyb** [comment]
I think you misread , it's saying that the real `DateTime` type should be used wherever possible, and that does have a `Generic` instance - it's not possible to provide `Generic` instances for foreign types, which is why `JSDate` doesn't have one.

**Comment by chexxor** [comment]
Oh my goodness! My mistake! Thanks @garyb - so kind!
