### ISSUE TITLE
EXCEPTION effect label err > exception

### ISSUE THREAD

**Issue by panthus** [purescript-contrib/purescript-js-date#9]
I think that ae7bfef6671883c5557ac6cff841f745fb0dfdec should be reverted now that the label has been renamed (https://github.com/purescript/purescript-exceptions/issues/19) 😄

**Comment by cprussin** [comment]
:+1:

**Comment by cprussin** [comment]
:+1: @garyb any reason not to do this?  This is making `toISOString` not play nice with `catchException`

**Comment by garyb** [comment]
Oh, no we should definitely do this! I didn't get a notification about the issue for some reason, thanks for the reminder.

**Comment by cprussin** [comment]
@garyb ping, I have a PR open for this but I can't merge it.  Also I don't know your release process.  Mind pulling it in?  Thanks!

**Comment by garyb** [comment]
Resolved by #10

**Comment by cprussin** [comment]
Many thanks @garyb!
